copy minedlg.cpp S:\alleg2\contrib\kgtools\ICE	
copy chaffdlg.cpp S:\alleg2\contrib\kgtools\ICE	
copy chaffdlg.h	 S:\alleg2\contrib\kgtools\ICE
copy civdlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy corestruct.h	S:\alleg2\contrib\kgtools\ICE
copy develdlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy dronedlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy dronedlg.h	S:\alleg2\contrib\kgtools\ICE
copy ice.aps S:\alleg2\contrib\kgtools\ICE
copy ice.ncb S:\alleg2\contrib\kgtools\ICE
copy ice.rc	S:\alleg2\contrib\kgtools\ICE
copy icedlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy icedlg.h	S:\alleg2\contrib\kgtools\ICE
copy igccore.cpp	S:\alleg2\contrib\kgtools\ICE
copy minedlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy minedlg.h	S:\alleg2\contrib\kgtools\ICE
copy missiledlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy missiledlg.h	S:\alleg2\contrib\kgtools\ICE
copy partdlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy partdlg.h	S:\alleg2\contrib\kgtools\ICE
copy probedlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy probedlg.h	S:\alleg2\contrib\kgtools\ICE
copy readme.txt	S:\alleg2\contrib\kgtools\ICE
copy resource.h	S:\alleg2\contrib\kgtools\ICE
copy shipdlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy shipdlg.h	S:\alleg2\contrib\kgtools\ICE
copy stationdlg.cpp	S:\alleg2\contrib\kgtools\ICE
copy treasuredlg.cpp	S:\alleg2\contrib\kgtools\ICE
