//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AGM.rc
//
#define IDDELETE                        3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AGM_DIALOG                  102
#define IDS_PROPERTIES                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_DELETE                      104
#define IDS_ADDBASE                     105
#define IDS_ADDROCK                     106
#define IDS_COPY                        107
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME1                  135
#define IDR_ACCELERATOR_SECTWND         137
#define IDD_GETNUMDLG                   139
#define IDR_VSINFO1                     143
#define IDD_SVRUI                       144
#define IDC_EDITRES                     1002
#define IDC_LockGameOpen                1003
#define IDC_LockTeamSettings            1004
#define IDC_InitialMinersPerTeam        1005
#define IDC_MaxMinersPerTeam            1006
#define IDC_AllowSupremacyPath          1007
#define IDC_AllowExpansionPath          1008
#define IDC_AllowTacticalPath           1009
#define IDC_AllowShipyardPath           1010
#define IDC_ShowMap                     1011
#define IDC_Teams                       1012
#define IDC_CivIDs1                     1013
#define IDC_CivIDs2                     1014
#define IDC_CivIDs3                     1015
#define IDC_CivIDs4                     1016
#define IDC_CivIDs5                     1017
#define IDC_CivIDs6                     1018
#define IDC_TeamName1                   1019
#define IDC_TeamName2                   1020
#define IDC_TeamName3                   1021
#define IDC_TeamName4                   1022
#define IDC_TeamName5                   1023
#define IDC_TeamName6                   1024
#define IDC_STATIC_TEAM1                1025
#define IDC_STATIC_TEAM2                1026
#define IDC_STATIC_TEAM3                1027
#define IDC_STATIC_TEAM4                1028
#define IDC_STATIC_TEAM5                1029
#define IDC_STATIC_TEAM6                1030
#define IDC_Drones                      1031
#define IDC_MaxImbalance                1032
#define IDC_StartingMoney               1033
#define IDC_TotalMaxPlayers             1034
#define IDC_He3Density                  1035
#define IDC_PlayerSectorMineableAsteroids 1036
#define IDC_NeutralSectorMineableAsteroids 1037
#define IDC_PlayerSectorSpecialAsteroids 1038
#define IDC_NeutralSectorSpecialAsteroids 1039
#define IDC_PlayerSectorAsteroids       1040
#define IDC_NeutralSectorAsteroids      1041
#define IDC_MinPlayers                  1042
#define IDC_GameName                    1043
#define IDC_StoryText                   1044
#define IDC_BUT_LOADREG                 1045
#define IDC_BUT_SAVEREG                 1046
#define IDC_BUT_About                   1047
#define IDC_MaxPlayers                  1048
#define IDC_CustomMap                   1049
#define IDC_BUT_MAP                     1050
#define IDC_BUT_LOADFILE                1051
#define IDC_BUT_SAVEFILE                1052
#define IDC_BUT_SAVEFILE2               1053
#define IDC_AllowEmptyTeams             1054
#define IDC_BUT_RESET                   1055
#define IDC_MapType                     1056
#define IDC_IsConquest                  1057
#define IDC_MAPEDIT                     1058
#define IDC_IsDM                        1059
#define IDC_DMKills                     1060
#define IDC_EjectPods                   1061
#define IDC_FriendlyFire                1062
#define IDC_Lives                       1063
#define IDC_StaticCore                  1064
#define IDC_BUT_CORE                    1065
#define IDC_IsMoney                     1066
#define IDC_StatsCount                  1067
#define IDC_GoalMoney                   1068
#define IDC_SquadGame                   1069
#define IDC_S_MAP                       1070
#define IDC_MapSize                     1071
#define IDC_S_CUSTMAP                   1072
#define IDC_NUMBER                      1207
#define IDC_CAPTION                     1208
#define IDC_GameLength                  1212
#define IDC_SERVERCORE                  1212
#define IDC_SVRBTCHANGE                 1225
#define IDC_SVRBTPARAMS                 1226
#define IDC_CHANGECORE                  1230
#define IDC_GAMESLIST                   1231
#define IDC_GAMEKILL                    1232
#define IDC_PLAYERLIST                  1233
#define IDC_SVRLOG                      1234
#define IDC_REFRESHGL                   1235
#define IDC_REFRESHGL2                  1236
#define IDC_REFRESHPL                   1236
#define IDC_PLAYERSLIST                 1237
#define IDC_CLEARLOG                    1238
#define IDC_PUBLICGAME                  1239
#define IDC_BUTTON1                     1240
#define IDC_LISTPLAYERS                 1242
#define DYNMENUSID                      5000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1243
#define _APS_NEXT_SYMED_VALUE           145
#endif
#endif
